CREATE TABLE  scan_docs (       
  id_doc NUMBER,                              
  nome varchar2(110) not null              
);                                            

COMMENT ON TABLE  scan_docs        IS 'Tabela informa os nomes dos documentos';
COMMENT ON COLUMN scan_docs.id_doc IS 'PK id do documento';
COMMENT ON COLUMN scan_docs.nome   IS 'nome do documento';


ALTER TABLE scan_docs
  ADD CONSTRAINT PK_scan_docs PRIMARY KEY (id_doc);


-- ALTER TABLE scan_docs add CONSTRAINT UNQ_scan_docs UNIQUE (id_nome);

GRANT INSERT, UPDATE, DELETE ON scan_docs TO RL_USUARIO_LETUPDATE;
GRANT SELECT ON scan_docs TO RL_USUARIO_READONLY;

CREATE OR REPLACE PUBLIC SYNONYM scan_docs FOR CM.scan_docs;


insert into  scan_docs (id_doc, nome)   
select id, nome from 
(
SELECT 1 ID, 'IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 2 ID, 'IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 3 ID, 'ULTIMO CONTRACHEQUE (PARTE DE DENTRO)'  NOME FROM DUAL UNION 
SELECT 4 ID, 'PENULTIMO CONTRACHEQUE (PARTE DE DENTRO)'  NOME FROM DUAL UNION 
SELECT 5 ID, 'COMPROVANTE DE RESIDENCIA'  NOME FROM DUAL UNION 
SELECT 6 ID, 'AUTORIZACAO DE CREDITO A TERCEIRO'  NOME FROM DUAL UNION 
SELECT 7 ID, 'CONTRATO (FRENTE)- CEDULA DE CREDITO BANIF'  NOME FROM DUAL UNION 
SELECT 8 ID, 'CONTRATO (VERSO) - CEDULA DE CREDITO BANIF'  NOME FROM DUAL UNION 
SELECT 10 ID, 'PROPOSTA PAG. 1'  NOME FROM DUAL UNION 
SELECT 11 ID, 'PROPOSTA PAG. 2'  NOME FROM DUAL UNION 
SELECT 12 ID, 'FICHA DE CADASTRO DO BANIF'  NOME FROM DUAL UNION 
SELECT 13 ID, 'CONTRATO MUTUO - GERADOR 13 (FRENTE)'  NOME FROM DUAL UNION 
SELECT 14 ID, 'CONTRATO MUTUO - GERADOR 13 (VERSO)'  NOME FROM DUAL UNION 
SELECT 15 ID, 'PRESTAMISTA - CARTAO PROPOSTA'  NOME FROM DUAL UNION 
SELECT 16 ID, 'AUTORIZACAO ESPECIAL PARA DEBITO AUTOMATICO'  NOME FROM DUAL UNION 
SELECT 17 ID, 'AUTORIZACAO DE AVERBACAO DE DESCONTO'  NOME FROM DUAL UNION 
SELECT 18 ID, 'EXTRATO DE AVERBACAO/RECIBO DE CONSIG/PRINT DA AVERBACAO'  NOME FROM DUAL UNION 
SELECT 19 ID, 'PRINT DA MARGEM NO PORTAL ANTES DA AVERBACAO'  NOME FROM DUAL UNION 
SELECT 20 ID, 'FITA DE CALCULO DA MARGEM'  NOME FROM DUAL UNION 
SELECT 21 ID, 'AUTORIZACAO DE INCLUSAO/EXCLUSAO DE DEBITO AUTOMATICO - SIACC'  NOME FROM DUAL UNION 
SELECT 22 ID, 'DECLARACAO PESSOAL DE SAUDE (DPS) - FL. 01 (QDO NECESSARIO)'  NOME FROM DUAL UNION 
SELECT 24 ID, 'DECLARACAO PESSOAL DE SAUDE (DPS) - FL. 02 (QDO NECESSARIO)'  NOME FROM DUAL UNION 
SELECT 25 ID, 'FBMC 700 (1/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 26 ID, 'FBMC 700 (2/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 27 ID, 'FBMC 700 (3/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 28 ID, 'FBMC 700 (4/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 29 ID, 'FBMC 737'  NOME FROM DUAL UNION 
SELECT 30 ID, 'FBMC 754'  NOME FROM DUAL UNION 
SELECT 31 ID, 'FBMC 828 PP'  NOME FROM DUAL UNION 
SELECT 32 ID, 'FBMC 867'  NOME FROM DUAL UNION 
SELECT 33 ID, 'FBMC 709 (1/2 PAGINA)'  NOME FROM DUAL UNION 
SELECT 34 ID, 'FBMC 709 (2/2 PAGINA)'  NOME FROM DUAL UNION 
SELECT 35 ID, 'ANTEPENULTIMO CONTRACHEQUE (PARTE DE DENTRO)'  NOME FROM DUAL UNION 
SELECT 36 ID, 'PROTOCOLO PARA TERMO DE ALTERACAO DA CONTRIBUICAO'  NOME FROM DUAL UNION 
SELECT 37 ID, 'TERMO DE ALTERACAO E RATIFICACAO DE PLANO PREVIDENCIARIO'  NOME FROM DUAL UNION 
SELECT 38 ID, 'REQUERIMENTO DE CANCELAMENTO (PLANO).'  NOME FROM DUAL UNION 
SELECT 39 ID, 'DECLARACAO DE RESIDENCIA. (NECESS QNDO O COMPRV Ñ ESTA NO NOME DO PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 40 ID, 'TERMO DE REDUCAO DE PLANO'  NOME FROM DUAL UNION 
SELECT 41 ID, 'PROTOCOLO PARA TERMO DE ALTERACAO DE CONTRIBUICAO'  NOME FROM DUAL UNION 
SELECT 42 ID, '2A. FOLHA CONTRACHEQUE ( CASO NECESSARIO )'  NOME FROM DUAL UNION 
SELECT 43 ID, '2A. FOLHA DO PENULTIMO CONTRACHEQUE ( CASO NECESSARIO )'  NOME FROM DUAL UNION 
SELECT 44 ID, 'CARTAO DE BENEFICIO ( FRENTE )'  NOME FROM DUAL UNION 
SELECT 45 ID, 'CARTAO DE BENEFICIO ( VERSO )'  NOME FROM DUAL UNION 
SELECT 46 ID, 'DETALHAMENTO DE CREDITO / DATAPREV'  NOME FROM DUAL UNION 
SELECT 47 ID, 'RECIBO DE AVERBACAO'  NOME FROM DUAL UNION 
SELECT 48 ID, 'FBMC 756 (1/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 49 ID, 'FBMC 756 (2/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 50 ID, 'FBMC 756 (3/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 51 ID, 'FBMC 756 (4/4 PAGINAS)'  NOME FROM DUAL UNION 
SELECT 52 ID, 'CERTIDAO DE OBITO'  NOME FROM DUAL UNION 
SELECT 53 ID, 'DOCUMENTO DO COMUNICANTE ( FRENTE )'  NOME FROM DUAL UNION 
SELECT 54 ID, 'AVISO DE SINISTRO'  NOME FROM DUAL UNION 
SELECT 55 ID, 'PCF'  NOME FROM DUAL UNION 
SELECT 56 ID, 'TERMO DE RESPONSABILIDADE DE SENHA'  NOME FROM DUAL UNION 
SELECT 57 ID, 'DOCUMENTO DO COMUNICANTE ( VERSO )'  NOME FROM DUAL UNION 
SELECT 58 ID, 'ENVELOPE DOS CORREIOS - CERTIDAO DE OBITO ( FRENTE ) '  NOME FROM DUAL UNION 
SELECT 59 ID, 'ENVELOPE DOS CORREIOS - CERTIDAO DE OBITO ( VERSO ) '  NOME FROM DUAL UNION 
SELECT 60 ID, 'CONTRACHEQUE (VERSO)'  NOME FROM DUAL UNION 
SELECT 61 ID, 'CARTA DE SOLICITACAO DO CANCELAMENTO PP ENVIADA PELO PARTICIPANTE'  NOME FROM DUAL UNION 
SELECT 62 ID, 'PROCURACAO (OBRIGATORIO QUANDO O CANCELAMENTO PP FOR REALIZADO VIA PROCURACAO)'  NOME FROM DUAL UNION 
SELECT 63 ID, 'DOCUMENTO DE IDENTIFICACAO DO PROCURADOR (OBRIGATORIO QUANDO O CANCELAMENTO PP FOR REALIZADO VIA PROCURACAO)'  NOME FROM DUAL UNION 
SELECT 64 ID, 'ENVELOPE DOS CORREIOS - CARTA (FRENTE)'  NOME FROM DUAL UNION 
SELECT 65 ID, 'ENVELOPE DOS CORREIOS - CARTA (VERSO)'  NOME FROM DUAL UNION 
SELECT 66 ID, 'TERMO DE AUTORIZACAO - SEGURO PRESTAMISTA'  NOME FROM DUAL UNION 
SELECT 67 ID, 'FICHA DE SOLICITACAO DE ASSISTENCIA FINANCEIRA PREVIMIL'  NOME FROM DUAL UNION 
SELECT 901 ID, 'DIVERSOS 01'  NOME FROM DUAL UNION 
SELECT 902 ID, 'DIVERSOS 02'  NOME FROM DUAL UNION 
SELECT 903 ID, 'DIVERSOS 03'  NOME FROM DUAL UNION 
SELECT 68 ID, 'PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 69 ID, 'REQUERIMENTO DE BENEFICIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 70 ID, 'CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 71 ID, 'COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 72 ID, 'DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 73 ID, 'COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 74 ID, 'CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 75 ID, 'ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 76 ID, 'DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 77 ID, 'CERTIDAO DE CASAMENTO OU NASCIMENTO (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 78 ID, 'RELATORIO MEDICO INDICANDO A CAUSA DA MORTE (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 79 ID, 'ULTIMO CONTRACHEQUE OU COMPROVANTE DE PAGAMENTO (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 80 ID, 'PENULTIMO CONTRACHEQUE OU COMPROVANTE DE PAGAMENTO (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 81 ID, 'ANTEPENULTIMO CONTRACHEQUE OU COMPROVANTE DE PAGAMENTO (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 82 ID, 'BOLETIM DE OCORRENCIA POLICIAL (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 83 ID, 'LAUDO DE NECROPSIA DO IML (PARTICIPANTE)'  NOME FROM DUAL UNION 
SELECT 84 ID, 'CADASTRO SIMPLIFICADO/PROPOSTA DA OPERACAO'  NOME FROM DUAL UNION 
SELECT 86 ID, 'AUTORIZACAO PARA DESCONTO EM FOLHA (DESDE QUE EXIGIDA PELO CONVENIO)'  NOME FROM DUAL UNION 
SELECT 87 ID, 'COMPROVANTE E RESERVA DE MARGEM A FAVOR DO BICBANCO'  NOME FROM DUAL UNION 
SELECT 88 ID, 'PROCURACAO PUBLICA'  NOME FROM DUAL UNION 
SELECT 89 ID, 'IDENTIDADE E O CPF DO PROCURADOR (FRENTE)'  NOME FROM DUAL UNION 
SELECT 90 ID, 'IDENTIDADE E O CPF DO PROCURADOR (VERSO)'  NOME FROM DUAL UNION 
SELECT 91 ID, 'AUTORIZACAO PARA REFINANCIAMENTO'  NOME FROM DUAL UNION 
SELECT 92 ID, 'AUTORIZACAO PARA LIQUIDACAO DE EMPRESTIMO EM OUTRA INSTITUICAO FINANCEIRA'  NOME FROM DUAL UNION 
SELECT 93 ID, 'CARTA DE SALDO DEVEDOR E/OU BOLETO BANCARIO'  NOME FROM DUAL UNION 
SELECT 94 ID, 'COMPROVANTE DE LIQUIDACAO DE SALDO DEVEDOR REFERENTE À INST. FIN. QUITADA'  NOME FROM DUAL UNION 
SELECT 85 ID, 'CEDULA DE CREDITO BANCARIO VIA NEGOCIAVEL'  NOME FROM DUAL UNION 
SELECT 95 ID, 'CEDULA DE CREDITO BANCARIO VIA NAO NEGOCIAVEL'  NOME FROM DUAL UNION 
SELECT 96 ID, 'AUTORIZACAO P/ DESCONTO, REFIN. E LIQUIDACAO INSS'  NOME FROM DUAL UNION 
SELECT 97 ID, 'PROTOCOLO DE SOLICITACAO E RECEBIMENTO DO SALDO DEVEDOR'  NOME FROM DUAL UNION 
SELECT 98 ID, 'FICHA DE SOLICITACAO DE A.F PREVIMIL - PG. 1 - POS ACEITE'  NOME FROM DUAL UNION 
SELECT 99 ID, 'PDAA - RECIBO DE QUITACAO'  NOME FROM DUAL UNION 
SELECT 100 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 101 ID, 'PDAA - AUTORIZACAO DE DESCONTO - PP'  NOME FROM DUAL UNION 
SELECT 102 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 103 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 104 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 105 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 106 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 107 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 108 ID, 'PDAA - AUTORIZACAO DE DESCONTO - AF'  NOME FROM DUAL UNION 
SELECT 109 ID, 'PDAA - AUTORIZACAO DE DESCONTO - PP'  NOME FROM DUAL UNION 
SELECT 110 ID, 'PDAA - AUTORIZACAO DE DESCONTO - PP'  NOME FROM DUAL UNION 
SELECT 111 ID, 'PDAA - AUTORIZACAO DE DESCONTO - PP'  NOME FROM DUAL UNION 
SELECT 112 ID, 'PDAA -  MEMORIA DE CALCULO'  NOME FROM DUAL UNION 
SELECT 113 ID, 'FICHA DE SOLICITACAO DE A.F PREVIMIL - PG. 2 - POS ACEITE'  NOME FROM DUAL UNION 
SELECT 114 ID, 'AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 115 ID, 'AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 116 ID, '01. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 117 ID, '01. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 118 ID, '01. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 119 ID, '01. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 120 ID, '01. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 121 ID, '01. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 122 ID, '01. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 123 ID, '01. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 124 ID, '01. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 125 ID, '01. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 126 ID, '01. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 127 ID, '01. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 128 ID, '01. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 129 ID, '02. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 130 ID, '02. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 131 ID, '02. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 132 ID, '02. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 133 ID, '02. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 134 ID, '02. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 135 ID, '02. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 136 ID, '02. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 137 ID, '02. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 138 ID, '02. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 139 ID, '02. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 140 ID, '02. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 141 ID, '02. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 142 ID, '03. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 143 ID, '03. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 144 ID, '03. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 145 ID, '03. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 146 ID, '03. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 147 ID, '03. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 148 ID, '03. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 149 ID, '03. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 150 ID, '03. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 151 ID, '03. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 152 ID, '03. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 153 ID, '03. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 154 ID, '03. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 155 ID, '04. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 156 ID, '04. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 157 ID, '04. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 158 ID, '04. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 159 ID, '04. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 160 ID, '04. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 161 ID, '04. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 162 ID, '04. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 163 ID, '04. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 164 ID, '04. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 165 ID, '04. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 166 ID, '04. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 167 ID, '04. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 168 ID, '05. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 169 ID, '05. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 170 ID, '05. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 171 ID, '05. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 172 ID, '05. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 173 ID, '05. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 174 ID, '05. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 175 ID, '05. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 176 ID, '05. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 177 ID, '05. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 178 ID, '05. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 179 ID, '05. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 180 ID, '05. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 181 ID, '06. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 182 ID, '06. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 183 ID, '06. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 184 ID, '06. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 185 ID, '06. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 186 ID, '06. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 187 ID, '06. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 188 ID, '06. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 189 ID, '06. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 190 ID, '06. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 191 ID, '06. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 192 ID, '06. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 193 ID, '06. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 194 ID, '07. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 195 ID, '07. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 196 ID, '07. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 197 ID, '07. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 198 ID, '07. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 199 ID, '07. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 200 ID, '07. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 201 ID, '07. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 202 ID, '07. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 203 ID, '07. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 204 ID, '07. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 205 ID, '07. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 206 ID, '07. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 207 ID, '08. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 208 ID, '08. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 209 ID, '08. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 210 ID, '08. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 211 ID, '08. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 212 ID, '08. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 213 ID, '08. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 214 ID, '08. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 215 ID, '08. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 216 ID, '08. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 217 ID, '08. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 218 ID, '08. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 219 ID, '08. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 220 ID, '09. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 221 ID, '09. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 222 ID, '09. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 223 ID, '09. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 224 ID, '09. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 225 ID, '09. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 226 ID, '09. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 227 ID, '09. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 228 ID, '09. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 229 ID, '09. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 230 ID, '09. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 231 ID, '09. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 232 ID, '09. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 233 ID, '10. IDENTIDADE E O CPF (FRENTE)'  NOME FROM DUAL UNION 
SELECT 234 ID, '10. IDENTIDADE E O CPF (VERSO)'  NOME FROM DUAL UNION 
SELECT 235 ID, '10. PROTOCOLO DE ENTREGA DE DOCUMENTOS E/OU ENVELOPE DOS CORREIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 236 ID, '10. REQUERIMENTO DE BENEFACIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 237 ID, '10. CERTIDAO DE CASAMENTO OU NASCIMENTO (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 238 ID, '10. COMPROVANTE DE RESIDENCIA, ATUALIZADO EM ATE 60 DIAS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 239 ID, '10. DECLARACAO DE RESIDENCIA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 240 ID, '10. COMPROVANTE DE DADOS BANCARIOS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 241 ID, '10. CERTIDAO DE TUTELA  OU CURATELA (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 242 ID, '10. ALVARA JUDICIAL (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 243 ID, '10. DECLARACAO DE HERDEIROS (BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 244 ID, '10. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MAIOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 245 ID, '10. AUTORIZACAO PARA CREDITO DE INDENIZACAO (MENOR BENEFICIARIO)'  NOME FROM DUAL UNION 
SELECT 246 ID, 'KIT PEC FLEX - FOLHA 1'  NOME FROM DUAL UNION 
SELECT 247 ID, 'KIT PEC FLEX - FOLHA 2'  NOME FROM DUAL UNION 
SELECT 248 ID, 'KIT PEC FLEX - FOLHA 3'  NOME FROM DUAL UNION 
SELECT 249 ID, 'AUTORIZACAO DO PEC FLEX'  NOME FROM DUAL UNION 
SELECT 250 ID, 'VERSO DO TERMO DE ALTERACAO E RATIFICACAO DE PLANO (DPS)'  NOME FROM DUAL UNION 
SELECT 251 ID, 'PROPOSTA PAG. 3' FROM DUAL );

commit;


CREATE TABLE  scan_oper (       
  id_oper NUMBER,                              
  operacao varchar2(25) not null,
  ativo number default  1 not null              
);                                            

COMMENT ON TABLE  scan_oper          IS 'Tabela informa os nomes das operações';
COMMENT ON COLUMN scan_oper.id_oper  IS 'PK id da operação';
COMMENT ON COLUMN scan_oper.operacao IS 'nome da operação';
COMMENT ON COLUMN scan_oper.ativo  IS 'Quando é uma operação ativa, 1 para mostra-la';


ALTER TABLE scan_oper
  ADD CONSTRAINT PK_scan_oper PRIMARY KEY (id_oper);
  
  
-- ALTER TABLE scan_oper ADD CONSTRAINT CK_scan_oper_01 scan_oper.ativo (ONOFF in ( 1, 0 ));


GRANT INSERT, UPDATE, DELETE ON scan_oper TO RL_USUARIO_LETUPDATE;
GRANT SELECT ON scan_oper TO RL_USUARIO_READONLY;

CREATE OR REPLACE PUBLIC SYNONYM scan_oper FOR CM.scan_oper;


insert into  scan_oper (id_oper, operacao, ativo)   
select id, nome, ativo from 
(
SELECT 1 id, 'Proposta' nome, 1 ativo FROM DUAL UNION 
SELECT 2, 'Benef - Aviso de Sinistro', 1  FROM DUAL UNION 
SELECT 3, 'BMC Militares - Compra', 0  FROM DUAL UNION 
SELECT 4, 'BMC Militares - NV/PAR', 0  FROM DUAL UNION 
SELECT 5, 'BMC Militares - REFIN', 0  FROM DUAL UNION 
SELECT 6, 'BMC SIAPE - Geral', 0  FROM DUAL UNION 
SELECT 7, 'BMC INSS - Compra', 0  FROM DUAL UNION 
SELECT 8, 'BMC INSS - NV/PAR', 0  FROM DUAL UNION 
SELECT 9, 'BMC INSS - REFIN', 0  FROM DUAL UNION 
SELECT 10, 'BMC Governo - Compra', 0  FROM DUAL UNION 
SELECT 11, 'BMC Governo - REFIN', 0  FROM DUAL UNION 
SELECT 12, 'BMC Governo - NV/PAR', 0  FROM DUAL UNION 
SELECT 13, 'Previmil - Aer - Refin', 1  FROM DUAL UNION 
SELECT 14, 'Previmil - Mex - Refin', 1  FROM DUAL UNION 
SELECT 15, 'Previmil - Mar - Refin', 1  FROM DUAL UNION 
SELECT 16, 'Previ- SIAPE - Refin', 1  FROM DUAL UNION 
SELECT 17, 'Cancelamento de plano', 1  FROM DUAL UNION 
SELECT 18, 'BICBANCO - Compra', 1  FROM DUAL UNION 
SELECT 19, 'BICBANCO - REFIN', 1  FROM DUAL UNION 
SELECT 20, 'BICBANCO - NV/PAR', 1  FROM DUAL UNION 
SELECT 21, 'SUL FIN. INSS - Compra', 0  FROM DUAL UNION 
SELECT 22, 'SUL FIN. INSS - NV/PAR', 0  FROM DUAL UNION 
SELECT 23, 'SUL FIN. INSS - REFIN', 0  FROM DUAL UNION 
SELECT 24, 'Alt status p/Debito Conta', 1  FROM DUAL UNION 
SELECT 25, 'PDAA', 1  FROM DUAL UNION 
SELECT 26, 'Benefício Processo', 1  FROM DUAL UNION 
SELECT 27, 'Previmil - Aer - Novo/Par', 1  FROM DUAL UNION 
SELECT 28, 'Previmil - Mex - Novo/Par', 1  FROM DUAL UNION 
SELECT 29, 'Previmil - Mar - Novo/Par', 1  FROM DUAL UNION 
SELECT 30, 'Previ- SIAPE - Novo/Par', 1 from dual
 );

commit;


CREATE TABLE  scan_operdocs (       
  id_oper NUMBER not null,                              
  id_doc number not null,
  obrig number(1) default 0 not null  
);    

COMMENT ON TABLE  scan_operdocs        IS 'Tabela informa os nomes dos documentos';
COMMENT ON COLUMN scan_operdocs.id_oper IS 'FK scan_docs';
COMMENT ON COLUMN scan_operdocs.id_doc   IS 'FK scan_oper';
COMMENT ON COLUMN scan_operdocs.obrig   IS 'Informa se o documento é obrigatorio';


ALTER TABLE scan_operdocs
  ADD CONSTRAINT PK_scan_operdocs PRIMARY KEY (id_oper, id_doc);

ALTER TABLE scan_operdocs
  ADD CONSTRAINT FK_scan_operdocs_01 FOREIGN KEY (id_doc)
     REFERENCES scan_docs (id_doc);

ALTER TABLE scan_operdocs
  ADD CONSTRAINT FK_scan_operdocs_02 FOREIGN KEY (id_oper)
     REFERENCES scan_oper (id_oper);

GRANT INSERT, UPDATE, DELETE ON scan_operdocs TO RL_USUARIO_LETUPDATE;
GRANT SELECT ON scan_operdocs TO RL_USUARIO_READONLY;

CREATE OR REPLACE PUBLIC SYNONYM scan_operdocs FOR CM.scan_operdocs;


insert into  scan_operdocs ( id_oper, id_doc, obrig)   
select a, b, c from 
(
SELECT 2 a, 52 b, 1 c  FROM DUAL UNION
SELECT 2, 53, 1  FROM DUAL UNION
SELECT 2, 54, 1  FROM DUAL UNION
SELECT 2, 57, 1  FROM DUAL UNION
SELECT 2, 58, 0  FROM DUAL UNION
SELECT 2, 59, 0  FROM DUAL UNION
SELECT 10, 1, 1  FROM DUAL UNION
SELECT 10, 2, 0  FROM DUAL UNION
SELECT 10, 28, 1  FROM DUAL UNION
SELECT 10, 3, 1  FROM DUAL UNION
SELECT 10, 5, 1  FROM DUAL UNION
SELECT 10, 55, 1  FROM DUAL UNION
SELECT 12, 1, 1  FROM DUAL UNION
SELECT 12, 2, 0  FROM DUAL UNION
SELECT 12, 28, 1  FROM DUAL UNION
SELECT 12, 3, 1  FROM DUAL UNION
SELECT 12, 5, 1  FROM DUAL UNION
SELECT 12, 55, 1  FROM DUAL UNION
SELECT 11, 1, 1  FROM DUAL UNION
SELECT 11, 2, 0  FROM DUAL UNION
SELECT 11, 28, 1  FROM DUAL UNION
SELECT 11, 3, 1  FROM DUAL UNION
SELECT 11, 5, 1  FROM DUAL UNION
SELECT 11, 55, 1  FROM DUAL UNION
SELECT 7, 1, 1  FROM DUAL UNION
SELECT 7, 2, 0  FROM DUAL UNION
SELECT 7, 28, 1  FROM DUAL UNION
SELECT 7, 34, 1  FROM DUAL UNION
SELECT 7, 46, 1  FROM DUAL UNION
SELECT 7, 5, 1  FROM DUAL UNION
SELECT 8, 1, 1  FROM DUAL UNION
SELECT 8, 2, 0  FROM DUAL UNION
SELECT 8, 28, 1  FROM DUAL UNION
SELECT 8, 46, 1  FROM DUAL UNION
SELECT 8, 5, 1  FROM DUAL UNION
SELECT 9, 1, 1  FROM DUAL UNION
SELECT 9, 2, 0  FROM DUAL UNION
SELECT 9, 28, 1  FROM DUAL UNION
SELECT 9, 30, 1  FROM DUAL UNION
SELECT 9, 46, 1  FROM DUAL UNION
SELECT 9, 5, 1  FROM DUAL UNION
SELECT 3, 1, 1  FROM DUAL UNION
SELECT 3, 2, 0  FROM DUAL UNION
SELECT 3, 28, 1  FROM DUAL UNION
SELECT 3, 29, 1  FROM DUAL UNION
SELECT 3, 3, 1  FROM DUAL UNION
SELECT 3, 30, 1  FROM DUAL UNION
SELECT 3, 34, 1  FROM DUAL UNION
SELECT 3, 5, 1  FROM DUAL UNION
SELECT 4, 1, 1  FROM DUAL UNION
SELECT 4, 2, 0  FROM DUAL UNION
SELECT 4, 28, 1  FROM DUAL UNION
SELECT 4, 29, 1  FROM DUAL UNION
SELECT 4, 3, 1  FROM DUAL UNION
SELECT 4, 5, 1  FROM DUAL UNION
SELECT 5, 1, 1  FROM DUAL UNION
SELECT 5, 2, 0  FROM DUAL UNION
SELECT 5, 28, 1  FROM DUAL UNION
SELECT 5, 29, 1  FROM DUAL UNION
SELECT 5, 3, 1  FROM DUAL UNION
SELECT 5, 30, 1  FROM DUAL UNION
SELECT 5, 5, 1  FROM DUAL UNION
SELECT 6, 1, 1  FROM DUAL UNION
SELECT 6, 2, 0  FROM DUAL UNION
SELECT 6, 28, 1  FROM DUAL UNION
SELECT 6, 3, 1  FROM DUAL UNION
SELECT 6, 31, 1  FROM DUAL UNION
SELECT 6, 34, 0  FROM DUAL UNION
SELECT 6, 5, 1  FROM DUAL UNION
SELECT 1, 1, 1  FROM DUAL UNION
SELECT 1, 10, 1  FROM DUAL UNION
SELECT 1, 11, 1  FROM DUAL UNION
SELECT 1, 2, 0  FROM DUAL UNION
SELECT 1, 22, 0  FROM DUAL UNION
SELECT 1, 24, 0  FROM DUAL UNION
SELECT 1, 3, 0  FROM DUAL UNION
SELECT 1, 39, 0  FROM DUAL UNION
SELECT 1, 4, 0  FROM DUAL UNION
SELECT 1, 5, 1  FROM DUAL UNION
SELECT 10, 40, 0  FROM DUAL UNION
SELECT 12, 40, 0  FROM DUAL UNION
SELECT 11, 40, 0  FROM DUAL UNION
SELECT 7, 40, 0  FROM DUAL UNION
SELECT 8, 40, 0  FROM DUAL UNION
SELECT 9, 40, 0  FROM DUAL UNION
SELECT 3, 40, 0  FROM DUAL UNION
SELECT 4, 40, 0  FROM DUAL UNION
SELECT 5, 40, 0  FROM DUAL UNION
SELECT 6, 40, 0  FROM DUAL UNION
SELECT 6, 30, 0  FROM DUAL UNION
SELECT 3, 67, 0  FROM DUAL UNION
SELECT 4, 67, 0  FROM DUAL UNION
SELECT 5, 67, 0  FROM DUAL UNION
SELECT 15, 1, 1  FROM DUAL UNION
SELECT 15, 2, 0  FROM DUAL UNION
SELECT 15, 5, 1  FROM DUAL UNION
SELECT 13, 1, 1  FROM DUAL UNION
SELECT 13, 2, 0  FROM DUAL UNION
SELECT 13, 3, 1  FROM DUAL UNION
SELECT 13, 5, 1  FROM DUAL UNION
SELECT 13, 67, 1  FROM DUAL UNION
SELECT 13, 15, 1  FROM DUAL UNION
SELECT 13, 66, 1  FROM DUAL UNION
SELECT 13, 16, 0  FROM DUAL UNION
SELECT 13, 18, 0  FROM DUAL UNION
SELECT 13, 21, 0  FROM DUAL UNION
SELECT 13, 36, 0  FROM DUAL UNION
SELECT 13, 37, 0  FROM DUAL UNION
SELECT 13, 38, 0  FROM DUAL UNION
SELECT 13, 39, 0  FROM DUAL UNION
SELECT 13, 42, 0  FROM DUAL UNION
SELECT 13, 60, 0  FROM DUAL UNION
SELECT 14, 1, 1  FROM DUAL UNION
SELECT 14, 2, 0  FROM DUAL UNION
SELECT 14, 3, 1  FROM DUAL UNION
SELECT 14, 5, 1  FROM DUAL UNION
SELECT 14, 15, 1  FROM DUAL UNION
SELECT 14, 16, 0  FROM DUAL UNION
SELECT 14, 18, 0  FROM DUAL UNION
SELECT 14, 19, 0  FROM DUAL UNION
SELECT 14, 21, 0  FROM DUAL UNION
SELECT 14, 36, 0  FROM DUAL UNION
SELECT 14, 37, 0  FROM DUAL UNION
SELECT 14, 38, 0  FROM DUAL UNION
SELECT 14, 39, 0  FROM DUAL UNION
SELECT 14, 42, 0  FROM DUAL UNION
SELECT 14, 60, 0  FROM DUAL UNION
SELECT 14, 67, 1  FROM DUAL UNION
SELECT 15, 4, 0  FROM DUAL UNION
SELECT 15, 67, 1  FROM DUAL UNION
SELECT 15, 16, 0  FROM DUAL UNION
SELECT 15, 21, 0  FROM DUAL UNION
SELECT 15, 36, 0  FROM DUAL UNION
SELECT 15, 37, 0  FROM DUAL UNION
SELECT 15, 38, 0  FROM DUAL UNION
SELECT 15, 39, 0  FROM DUAL UNION
SELECT 15, 42, 0  FROM DUAL UNION
SELECT 15, 60, 0  FROM DUAL UNION
SELECT 16, 1, 1  FROM DUAL UNION
SELECT 16, 2, 0  FROM DUAL UNION
SELECT 16, 3, 1  FROM DUAL UNION
SELECT 16, 4, 0  FROM DUAL UNION
SELECT 16, 5, 1  FROM DUAL UNION
SELECT 16, 15, 1  FROM DUAL UNION
SELECT 16, 16, 0  FROM DUAL UNION
SELECT 16, 21, 0  FROM DUAL UNION
SELECT 16, 36, 0  FROM DUAL UNION
SELECT 16, 37, 0  FROM DUAL UNION
SELECT 16, 38, 0  FROM DUAL UNION
SELECT 16, 39, 0  FROM DUAL UNION
SELECT 16, 42, 0  FROM DUAL UNION
SELECT 16, 43, 0  FROM DUAL UNION
SELECT 16, 56, 0  FROM DUAL UNION
SELECT 16, 60, 0  FROM DUAL UNION
SELECT 16, 67, 1  FROM DUAL UNION
SELECT 16, 66, 1  FROM DUAL UNION
SELECT 17, 1, 1  FROM DUAL UNION
SELECT 17, 2, 0  FROM DUAL UNION
SELECT 17, 38, 0  FROM DUAL UNION
SELECT 17, 61, 0  FROM DUAL UNION
SELECT 17, 62, 0  FROM DUAL UNION
SELECT 17, 63, 0  FROM DUAL UNION
SELECT 17, 64, 0  FROM DUAL UNION
SELECT 17, 65, 0  FROM DUAL UNION
SELECT 10, 901, 0  FROM DUAL UNION
SELECT 12, 901, 0  FROM DUAL UNION
SELECT 10, 902, 0  FROM DUAL UNION
SELECT 10, 903, 0  FROM DUAL UNION
SELECT 12, 902, 0  FROM DUAL UNION
SELECT 12, 903, 0  FROM DUAL UNION
SELECT 11, 901, 0  FROM DUAL UNION
SELECT 11, 902, 0  FROM DUAL UNION
SELECT 11, 903, 0  FROM DUAL UNION
SELECT 7, 901, 0  FROM DUAL UNION
SELECT 7, 902, 0  FROM DUAL UNION
SELECT 7, 903, 0  FROM DUAL UNION
SELECT 8, 901, 0  FROM DUAL UNION
SELECT 8, 902, 0  FROM DUAL UNION
SELECT 8, 903, 0  FROM DUAL UNION
SELECT 9, 901, 0  FROM DUAL UNION
SELECT 9, 902, 0  FROM DUAL UNION
SELECT 9, 903, 0  FROM DUAL UNION
SELECT 3, 901, 0  FROM DUAL UNION
SELECT 3, 902, 0  FROM DUAL UNION
SELECT 3, 903, 0  FROM DUAL UNION
SELECT 4, 901, 0  FROM DUAL UNION
SELECT 4, 902, 0  FROM DUAL UNION
SELECT 4, 903, 0  FROM DUAL UNION
SELECT 5, 901, 0  FROM DUAL UNION
SELECT 5, 902, 0  FROM DUAL UNION
SELECT 5, 903, 0  FROM DUAL UNION
SELECT 6, 901, 0  FROM DUAL UNION
SELECT 6, 902, 0  FROM DUAL UNION
SELECT 6, 903, 0  FROM DUAL UNION
SELECT 1, 901, 0  FROM DUAL UNION
SELECT 1, 902, 0  FROM DUAL UNION
SELECT 1, 903, 0  FROM DUAL UNION
SELECT 16, 901, 0  FROM DUAL UNION
SELECT 16, 902, 0  FROM DUAL UNION
SELECT 16, 903, 0  FROM DUAL UNION
SELECT 15, 901, 0  FROM DUAL UNION
SELECT 15, 902, 0  FROM DUAL UNION
SELECT 15, 903, 0  FROM DUAL UNION
SELECT 14, 901, 0  FROM DUAL UNION
SELECT 14, 902, 0  FROM DUAL UNION
SELECT 14, 903, 0  FROM DUAL UNION
SELECT 13, 901, 0  FROM DUAL UNION
SELECT 13, 902, 0  FROM DUAL UNION
SELECT 13, 903, 0  FROM DUAL UNION
SELECT 17, 901, 0  FROM DUAL UNION
SELECT 17, 902, 0  FROM DUAL UNION
SELECT 17, 903, 0  FROM DUAL UNION
SELECT 2, 901, 0  FROM DUAL UNION
SELECT 2, 902, 0  FROM DUAL UNION
SELECT 2, 903, 0  FROM DUAL UNION
SELECT 2, 1, 0  FROM DUAL UNION
SELECT 2, 68, 0  FROM DUAL UNION
SELECT 2, 69, 0  FROM DUAL UNION
SELECT 2, 70, 0  FROM DUAL UNION
SELECT 2, 71, 0  FROM DUAL UNION
SELECT 2, 72, 0  FROM DUAL UNION
SELECT 2, 73, 0  FROM DUAL UNION
SELECT 2, 74, 0  FROM DUAL UNION
SELECT 2, 75, 0  FROM DUAL UNION
SELECT 2, 76, 0  FROM DUAL UNION
SELECT 2, 77, 0  FROM DUAL UNION
SELECT 2, 78, 0  FROM DUAL UNION
SELECT 2, 79, 0  FROM DUAL UNION
SELECT 2, 80, 0  FROM DUAL UNION
SELECT 2, 81, 0  FROM DUAL UNION
SELECT 2, 82, 0  FROM DUAL UNION
SELECT 2, 83, 0  FROM DUAL UNION
SELECT 20, 1, 1  FROM DUAL UNION
SELECT 20, 2, 1  FROM DUAL UNION
SELECT 20, 3, 1  FROM DUAL UNION
SELECT 20, 5, 1  FROM DUAL UNION
SELECT 20, 40, 0  FROM DUAL UNION
SELECT 20, 84, 1  FROM DUAL UNION
SELECT 20, 86, 0  FROM DUAL UNION
SELECT 20, 87, 0  FROM DUAL UNION
SELECT 20, 88, 0  FROM DUAL UNION
SELECT 20, 89, 0  FROM DUAL UNION
SELECT 20, 90, 0  FROM DUAL UNION
SELECT 20, 901, 0  FROM DUAL UNION
SELECT 20, 902, 0  FROM DUAL UNION
SELECT 20, 903, 0  FROM DUAL UNION
SELECT 19, 1, 1  FROM DUAL UNION
SELECT 19, 2, 1  FROM DUAL UNION
SELECT 19, 3, 1  FROM DUAL UNION
SELECT 19, 5, 1  FROM DUAL UNION
SELECT 19, 40, 0  FROM DUAL UNION
SELECT 19, 84, 1  FROM DUAL UNION
SELECT 19, 91, 1  FROM DUAL UNION
SELECT 19, 86, 0  FROM DUAL UNION
SELECT 19, 87, 0  FROM DUAL UNION
SELECT 19, 88, 0  FROM DUAL UNION
SELECT 19, 89, 0  FROM DUAL UNION
SELECT 19, 90, 0  FROM DUAL UNION
SELECT 19, 901, 0  FROM DUAL UNION
SELECT 19, 902, 0  FROM DUAL UNION
SELECT 19, 903, 0  FROM DUAL UNION
SELECT 18, 1, 1  FROM DUAL UNION
SELECT 18, 2, 1  FROM DUAL UNION
SELECT 18, 3, 1  FROM DUAL UNION
SELECT 18, 5, 1  FROM DUAL UNION
SELECT 18, 40, 0  FROM DUAL UNION
SELECT 18, 84, 1  FROM DUAL UNION
SELECT 18, 92, 1  FROM DUAL UNION
SELECT 18, 93, 1  FROM DUAL UNION
SELECT 18, 86, 0  FROM DUAL UNION
SELECT 18, 87, 0  FROM DUAL UNION
SELECT 18, 88, 0  FROM DUAL UNION
SELECT 18, 89, 0  FROM DUAL UNION
SELECT 18, 90, 0  FROM DUAL UNION
SELECT 18, 901, 0  FROM DUAL UNION
SELECT 18, 902, 0  FROM DUAL UNION
SELECT 18, 903, 0  FROM DUAL UNION
SELECT 18, 94, 0  FROM DUAL UNION
SELECT 18, 85, 1  FROM DUAL UNION
SELECT 20, 85, 1  FROM DUAL UNION
SELECT 19, 85, 1  FROM DUAL UNION
SELECT 21, 1, 1  FROM DUAL UNION
SELECT 21, 2, 1  FROM DUAL UNION
SELECT 21, 46, 1  FROM DUAL UNION
SELECT 21, 5, 1  FROM DUAL UNION
SELECT 21, 40, 0  FROM DUAL UNION
SELECT 21, 84, 1  FROM DUAL UNION
SELECT 21, 85, 1  FROM DUAL UNION
SELECT 21, 96, 1  FROM DUAL UNION
SELECT 21, 88, 0  FROM DUAL UNION
SELECT 21, 89, 0  FROM DUAL UNION
SELECT 21, 90, 0  FROM DUAL UNION
SELECT 21, 901, 0  FROM DUAL UNION
SELECT 21, 902, 0  FROM DUAL UNION
SELECT 21, 903, 0  FROM DUAL UNION
SELECT 22, 1, 1  FROM DUAL UNION
SELECT 22, 2, 1  FROM DUAL UNION
SELECT 22, 5, 1  FROM DUAL UNION
SELECT 22, 40, 0  FROM DUAL UNION
SELECT 22, 46, 1  FROM DUAL UNION
SELECT 22, 84, 1  FROM DUAL UNION
SELECT 22, 85, 1  FROM DUAL UNION
SELECT 22, 88, 0  FROM DUAL UNION
SELECT 22, 89, 0  FROM DUAL UNION
SELECT 22, 90, 0  FROM DUAL UNION
SELECT 22, 96, 1  FROM DUAL UNION
SELECT 22, 901, 0  FROM DUAL UNION
SELECT 22, 902, 0  FROM DUAL UNION
SELECT 22, 903, 0  FROM DUAL UNION
SELECT 23, 1, 1  FROM DUAL UNION
SELECT 23, 2, 1  FROM DUAL UNION
SELECT 23, 5, 1  FROM DUAL UNION
SELECT 23, 40, 0  FROM DUAL UNION
SELECT 23, 46, 1  FROM DUAL UNION
SELECT 23, 84, 1  FROM DUAL UNION
SELECT 23, 85, 1  FROM DUAL UNION
SELECT 23, 88, 0  FROM DUAL UNION
SELECT 23, 89, 0  FROM DUAL UNION
SELECT 23, 90, 0  FROM DUAL UNION
SELECT 23, 96, 1  FROM DUAL UNION
SELECT 23, 901, 0  FROM DUAL UNION
SELECT 23, 902, 0  FROM DUAL UNION
SELECT 23, 903, 0  FROM DUAL UNION
SELECT 18, 95, 1  FROM DUAL UNION
SELECT 20, 95, 1  FROM DUAL UNION
SELECT 19, 95, 1  FROM DUAL UNION
SELECT 21, 95, 1  FROM DUAL UNION
SELECT 22, 95, 1  FROM DUAL UNION
SELECT 23, 95, 1  FROM DUAL UNION
SELECT 1, 16, 1  FROM DUAL UNION
SELECT 24, 1, 1  FROM DUAL UNION
SELECT 24, 2, 0  FROM DUAL UNION
SELECT 24, 901, 0  FROM DUAL UNION
SELECT 24, 902, 0  FROM DUAL UNION
SELECT 24, 903, 0  FROM DUAL UNION
SELECT 24, 16, 1  FROM DUAL UNION
SELECT 13, 97, 0  FROM DUAL UNION
SELECT 14, 97, 0  FROM DUAL UNION
SELECT 15, 97, 0  FROM DUAL UNION
SELECT 16, 97, 0  FROM DUAL UNION
SELECT 13, 98, 0  FROM DUAL UNION
SELECT 14, 98, 0  FROM DUAL UNION
SELECT 15, 98, 0  FROM DUAL UNION
SELECT 16, 98, 0  FROM DUAL UNION
SELECT 25, 1, 1  FROM DUAL UNION
SELECT 25, 2, 0  FROM DUAL UNION
SELECT 25, 5, 1  FROM DUAL UNION
SELECT 25, 99, 1  FROM DUAL UNION
SELECT 25, 100, 0  FROM DUAL UNION
SELECT 25, 101, 0  FROM DUAL UNION
SELECT 25, 102, 0  FROM DUAL UNION
SELECT 25, 103, 0  FROM DUAL UNION
SELECT 25, 104, 0  FROM DUAL UNION
SELECT 25, 105, 0  FROM DUAL UNION
SELECT 25, 106, 0  FROM DUAL UNION
SELECT 25, 107, 0  FROM DUAL UNION
SELECT 25, 108, 0  FROM DUAL UNION
SELECT 25, 109, 0  FROM DUAL UNION
SELECT 25, 110, 0  FROM DUAL UNION
SELECT 25, 111, 0  FROM DUAL UNION
SELECT 25, 112, 0  FROM DUAL UNION
SELECT 25, 39, 0  FROM DUAL UNION
SELECT 25, 901, 0  FROM DUAL UNION
SELECT 13, 113, 0  FROM DUAL UNION
SELECT 14, 113, 0  FROM DUAL UNION
SELECT 15, 113, 0  FROM DUAL UNION
SELECT 16, 113, 0  FROM DUAL UNION
SELECT 2, 2, 0  FROM DUAL UNION
SELECT 2, 10, 0  FROM DUAL UNION
SELECT 2, 11, 0  FROM DUAL UNION
SELECT 26, 1, 0  FROM DUAL UNION
SELECT 26, 2, 0  FROM DUAL UNION
SELECT 26, 52, 0  FROM DUAL UNION
SELECT 26, 53, 0  FROM DUAL UNION
SELECT 26, 54, 0  FROM DUAL UNION
SELECT 26, 57, 0  FROM DUAL UNION
SELECT 26, 58, 0  FROM DUAL UNION
SELECT 26, 59, 0  FROM DUAL UNION
SELECT 26, 116, 0  FROM DUAL UNION
SELECT 26, 117, 0  FROM DUAL UNION
SELECT 26, 118, 0  FROM DUAL UNION
SELECT 26, 119, 0  FROM DUAL UNION
SELECT 26, 120, 0  FROM DUAL UNION
SELECT 26, 121, 0  FROM DUAL UNION
SELECT 26, 122, 0  FROM DUAL UNION
SELECT 26, 123, 0  FROM DUAL UNION
SELECT 26, 124, 0  FROM DUAL UNION
SELECT 26, 125, 0  FROM DUAL UNION
SELECT 26, 126, 0  FROM DUAL UNION
SELECT 26, 127, 0  FROM DUAL UNION
SELECT 26, 128, 0  FROM DUAL UNION
SELECT 26, 129, 0  FROM DUAL UNION
SELECT 26, 130, 0  FROM DUAL UNION
SELECT 26, 131, 0  FROM DUAL UNION
SELECT 26, 132, 0  FROM DUAL UNION
SELECT 26, 133, 0  FROM DUAL UNION
SELECT 26, 134, 0  FROM DUAL UNION
SELECT 26, 135, 0  FROM DUAL UNION
SELECT 26, 136, 0  FROM DUAL UNION
SELECT 26, 137, 0  FROM DUAL UNION
SELECT 26, 138, 0  FROM DUAL UNION
SELECT 26, 139, 0  FROM DUAL UNION
SELECT 26, 140, 0  FROM DUAL UNION
SELECT 26, 141, 0  FROM DUAL UNION
SELECT 26, 142, 0  FROM DUAL UNION
SELECT 26, 143, 0  FROM DUAL UNION
SELECT 26, 144, 0  FROM DUAL UNION
SELECT 26, 145, 0  FROM DUAL UNION
SELECT 26, 146, 0  FROM DUAL UNION
SELECT 26, 147, 0  FROM DUAL UNION
SELECT 26, 148, 0  FROM DUAL UNION
SELECT 26, 149, 0  FROM DUAL UNION
SELECT 26, 150, 0  FROM DUAL UNION
SELECT 26, 151, 0  FROM DUAL UNION
SELECT 26, 152, 0  FROM DUAL UNION
SELECT 26, 153, 0  FROM DUAL UNION
SELECT 26, 154, 0  FROM DUAL UNION
SELECT 26, 155, 0  FROM DUAL UNION
SELECT 26, 156, 0  FROM DUAL UNION
SELECT 26, 157, 0  FROM DUAL UNION
SELECT 26, 158, 0  FROM DUAL UNION
SELECT 26, 159, 0  FROM DUAL UNION
SELECT 26, 160, 0  FROM DUAL UNION
SELECT 26, 161, 0  FROM DUAL UNION
SELECT 26, 162, 0  FROM DUAL UNION
SELECT 26, 163, 0  FROM DUAL UNION
SELECT 26, 164, 0  FROM DUAL UNION
SELECT 26, 165, 0  FROM DUAL UNION
SELECT 26, 166, 0  FROM DUAL UNION
SELECT 26, 167, 0  FROM DUAL UNION
SELECT 26, 168, 0  FROM DUAL UNION
SELECT 26, 169, 0  FROM DUAL UNION
SELECT 26, 170, 0  FROM DUAL UNION
SELECT 26, 171, 0  FROM DUAL UNION
SELECT 26, 172, 0  FROM DUAL UNION
SELECT 26, 173, 0  FROM DUAL UNION
SELECT 26, 174, 0  FROM DUAL UNION
SELECT 26, 175, 0  FROM DUAL UNION
SELECT 26, 176, 0  FROM DUAL UNION
SELECT 26, 177, 0  FROM DUAL UNION
SELECT 26, 178, 0  FROM DUAL UNION
SELECT 26, 179, 0  FROM DUAL UNION
SELECT 26, 180, 0  FROM DUAL UNION
SELECT 26, 181, 0  FROM DUAL UNION
SELECT 26, 182, 0  FROM DUAL UNION
SELECT 26, 183, 0  FROM DUAL UNION
SELECT 26, 184, 0  FROM DUAL UNION
SELECT 26, 185, 0  FROM DUAL UNION
SELECT 26, 186, 0  FROM DUAL UNION
SELECT 26, 187, 0  FROM DUAL UNION
SELECT 26, 188, 0  FROM DUAL UNION
SELECT 26, 189, 0  FROM DUAL UNION
SELECT 26, 190, 0  FROM DUAL UNION
SELECT 26, 191, 0  FROM DUAL UNION
SELECT 26, 192, 0  FROM DUAL UNION
SELECT 26, 193, 0  FROM DUAL UNION
SELECT 26, 194, 0  FROM DUAL UNION
SELECT 26, 195, 0  FROM DUAL UNION
SELECT 26, 196, 0  FROM DUAL UNION
SELECT 26, 197, 0  FROM DUAL UNION
SELECT 26, 198, 0  FROM DUAL UNION
SELECT 26, 199, 0  FROM DUAL UNION
SELECT 26, 200, 0  FROM DUAL UNION
SELECT 26, 201, 0  FROM DUAL UNION
SELECT 26, 202, 0  FROM DUAL UNION
SELECT 26, 203, 0  FROM DUAL UNION
SELECT 26, 204, 0  FROM DUAL UNION
SELECT 26, 205, 0  FROM DUAL UNION
SELECT 26, 206, 0  FROM DUAL UNION
SELECT 26, 207, 0  FROM DUAL UNION
SELECT 26, 208, 0  FROM DUAL UNION
SELECT 26, 209, 0  FROM DUAL UNION
SELECT 26, 210, 0  FROM DUAL UNION
SELECT 26, 211, 0  FROM DUAL UNION
SELECT 26, 212, 0  FROM DUAL UNION
SELECT 26, 213, 0  FROM DUAL UNION
SELECT 26, 214, 0  FROM DUAL UNION
SELECT 26, 215, 0  FROM DUAL UNION
SELECT 26, 216, 0  FROM DUAL UNION
SELECT 26, 217, 0  FROM DUAL UNION
SELECT 26, 218, 0  FROM DUAL UNION
SELECT 26, 219, 0  FROM DUAL UNION
SELECT 26, 220, 0  FROM DUAL UNION
SELECT 26, 221, 0  FROM DUAL UNION
SELECT 26, 222, 0  FROM DUAL UNION
SELECT 26, 223, 0  FROM DUAL UNION
SELECT 26, 224, 0  FROM DUAL UNION
SELECT 26, 225, 0  FROM DUAL UNION
SELECT 26, 226, 0  FROM DUAL UNION
SELECT 26, 227, 0  FROM DUAL UNION
SELECT 26, 228, 0  FROM DUAL UNION
SELECT 26, 229, 0  FROM DUAL UNION
SELECT 26, 230, 0  FROM DUAL UNION
SELECT 26, 231, 0  FROM DUAL UNION
SELECT 26, 232, 0  FROM DUAL UNION
SELECT 26, 233, 0  FROM DUAL UNION
SELECT 26, 234, 0  FROM DUAL UNION
SELECT 26, 235, 0  FROM DUAL UNION
SELECT 26, 236, 0  FROM DUAL UNION
SELECT 26, 237, 0  FROM DUAL UNION
SELECT 26, 238, 0  FROM DUAL UNION
SELECT 26, 239, 0  FROM DUAL UNION
SELECT 26, 240, 0  FROM DUAL UNION
SELECT 26, 241, 0  FROM DUAL UNION
SELECT 26, 242, 0  FROM DUAL UNION
SELECT 26, 243, 0  FROM DUAL UNION
SELECT 26, 244, 0  FROM DUAL UNION
SELECT 26, 245, 0  FROM DUAL UNION
SELECT 27, 1, 1  FROM DUAL UNION
SELECT 27, 2, 0  FROM DUAL UNION
SELECT 27, 3, 1  FROM DUAL UNION
SELECT 27, 5, 1  FROM DUAL UNION
SELECT 27, 15, 1  FROM DUAL UNION
SELECT 27, 16, 0  FROM DUAL UNION
SELECT 27, 18, 0  FROM DUAL UNION
SELECT 27, 21, 0  FROM DUAL UNION
SELECT 27, 36, 0  FROM DUAL UNION
SELECT 27, 37, 0  FROM DUAL UNION
SELECT 27, 38, 0  FROM DUAL UNION
SELECT 27, 39, 0  FROM DUAL UNION
SELECT 27, 42, 0  FROM DUAL UNION
SELECT 27, 60, 0  FROM DUAL UNION
SELECT 27, 66, 1  FROM DUAL UNION
SELECT 27, 67, 1  FROM DUAL UNION
SELECT 27, 97, 0  FROM DUAL UNION
SELECT 27, 98, 0  FROM DUAL UNION
SELECT 27, 113, 0  FROM DUAL UNION
SELECT 27, 901, 0  FROM DUAL UNION
SELECT 27, 902, 0  FROM DUAL UNION
SELECT 27, 903, 0  FROM DUAL UNION
SELECT 27, 4, 1  FROM DUAL UNION
SELECT 27, 35, 1  FROM DUAL UNION
SELECT 27, 250, 0  FROM DUAL UNION
SELECT 29, 1, 1  FROM DUAL UNION
SELECT 29, 2, 0  FROM DUAL UNION
SELECT 29, 5, 1  FROM DUAL UNION
SELECT 29, 4, 1  FROM DUAL UNION
SELECT 29, 16, 0  FROM DUAL UNION
SELECT 29, 21, 0  FROM DUAL UNION
SELECT 29, 36, 0  FROM DUAL UNION
SELECT 29, 38, 0  FROM DUAL UNION
SELECT 29, 39, 0  FROM DUAL UNION
SELECT 29, 42, 0  FROM DUAL UNION
SELECT 29, 60, 0  FROM DUAL UNION
SELECT 29, 67, 1  FROM DUAL UNION
SELECT 29, 97, 0  FROM DUAL UNION
SELECT 29, 98, 0  FROM DUAL UNION
SELECT 29, 250, 0  FROM DUAL UNION
SELECT 29, 113, 0  FROM DUAL UNION
SELECT 29, 901, 0  FROM DUAL UNION
SELECT 29, 902, 0  FROM DUAL UNION
SELECT 29, 903, 0  FROM DUAL UNION
SELECT 29, 35, 0  FROM DUAL UNION
SELECT 28, 1, 1  FROM DUAL UNION
SELECT 28, 2, 0  FROM DUAL UNION
SELECT 28, 5, 1  FROM DUAL UNION
SELECT 28, 15, 1  FROM DUAL UNION
SELECT 28, 16, 0  FROM DUAL UNION
SELECT 28, 18, 0  FROM DUAL UNION
SELECT 28, 19, 0  FROM DUAL UNION
SELECT 28, 21, 0  FROM DUAL UNION
SELECT 28, 36, 0  FROM DUAL UNION
SELECT 28, 37, 0  FROM DUAL UNION
SELECT 28, 38, 0  FROM DUAL UNION
SELECT 28, 39, 0  FROM DUAL UNION
SELECT 28, 42, 0  FROM DUAL UNION
SELECT 28, 60, 0  FROM DUAL UNION
SELECT 28, 67, 1  FROM DUAL UNION
SELECT 28, 901, 0  FROM DUAL UNION
SELECT 28, 902, 0  FROM DUAL UNION
SELECT 28, 903, 0  FROM DUAL UNION
SELECT 28, 97, 0  FROM DUAL UNION
SELECT 28, 98, 0  FROM DUAL UNION
SELECT 28, 113, 0  FROM DUAL UNION
SELECT 28, 3, 1  FROM DUAL UNION
SELECT 28, 4, 1  FROM DUAL UNION
SELECT 28, 35, 1  FROM DUAL UNION
SELECT 28, 250, 0  FROM DUAL UNION
SELECT 30, 1, 1  FROM DUAL UNION
SELECT 30, 2, 0  FROM DUAL UNION
SELECT 30, 3, 1  FROM DUAL UNION
SELECT 30, 4, 1  FROM DUAL UNION
SELECT 30, 5, 1  FROM DUAL UNION
SELECT 30, 15, 1  FROM DUAL UNION
SELECT 30, 16, 0  FROM DUAL UNION
SELECT 30, 21, 0  FROM DUAL UNION
SELECT 30, 36, 0  FROM DUAL UNION
SELECT 30, 37, 0  FROM DUAL UNION
SELECT 30, 38, 0  FROM DUAL UNION
SELECT 30, 39, 0  FROM DUAL UNION
SELECT 30, 42, 0  FROM DUAL UNION
SELECT 30, 43, 0  FROM DUAL UNION
SELECT 30, 56, 0  FROM DUAL UNION
SELECT 30, 60, 0  FROM DUAL UNION
SELECT 30, 66, 1  FROM DUAL UNION
SELECT 30, 67, 1  FROM DUAL UNION
SELECT 30, 901, 0  FROM DUAL UNION
SELECT 30, 902, 0  FROM DUAL UNION
SELECT 30, 903, 0  FROM DUAL UNION
SELECT 30, 97, 0  FROM DUAL UNION
SELECT 30, 98, 0  FROM DUAL UNION
SELECT 30, 113, 0  FROM DUAL UNION
SELECT 16, 246, 0  FROM DUAL UNION
SELECT 16, 247, 0  FROM DUAL UNION
SELECT 16, 248, 0  FROM DUAL UNION
SELECT 16, 249, 0  FROM DUAL UNION
SELECT 16, 250, 0  FROM DUAL UNION
SELECT 30, 250, 0  FROM DUAL UNION
SELECT 13, 246, 0  FROM DUAL UNION
SELECT 13, 247, 0  FROM DUAL UNION
SELECT 13, 248, 0  FROM DUAL UNION
SELECT 13, 249, 0  FROM DUAL UNION
SELECT 13, 250, 0  FROM DUAL UNION
SELECT 15, 246, 0  FROM DUAL UNION
SELECT 15, 247, 0  FROM DUAL UNION
SELECT 15, 248, 0  FROM DUAL UNION
SELECT 15, 249, 0  FROM DUAL UNION
SELECT 15, 250, 0  FROM DUAL UNION
SELECT 27, 19, 0  FROM DUAL UNION
SELECT 13, 19, 0  FROM DUAL UNION
SELECT 29, 18, 0  FROM DUAL UNION
SELECT 29, 19, 0  FROM DUAL UNION
SELECT 15, 18, 0  FROM DUAL UNION
SELECT 15, 19, 0  FROM DUAL UNION
SELECT 30, 18, 0  FROM DUAL UNION
SELECT 30, 19, 0  FROM DUAL UNION
SELECT 16, 18, 0  FROM DUAL UNION
SELECT 16, 19, 0  FROM DUAL UNION
SELECT 30, 22, 0  FROM DUAL UNION
SELECT 30, 24, 0  FROM DUAL UNION
SELECT 16, 22, 0  FROM DUAL UNION
SELECT 16, 24, 0  FROM DUAL UNION
SELECT 27, 22, 0  FROM DUAL UNION
SELECT 27, 24, 0  FROM DUAL UNION
SELECT 13, 22, 0  FROM DUAL UNION
SELECT 13, 24, 0  FROM DUAL UNION
SELECT 29, 22, 0  FROM DUAL UNION
SELECT 29, 24, 0  FROM DUAL UNION
SELECT 15, 24, 0  FROM DUAL UNION
SELECT 15, 22, 0  FROM DUAL UNION
SELECT 28, 22, 0  FROM DUAL UNION
SELECT 28, 24, 0  FROM DUAL UNION
SELECT 30, 35, 1  FROM DUAL UNION
SELECT 16, 35, 0  FROM DUAL UNION
SELECT 27, 43, 0  FROM DUAL UNION
SELECT 27, 56, 0  FROM DUAL UNION
SELECT 13, 4, 0  FROM DUAL UNION
SELECT 13, 43, 0  FROM DUAL UNION
SELECT 13, 56, 0  FROM DUAL UNION
SELECT 29, 3, 1  FROM DUAL UNION
SELECT 29, 37, 0  FROM DUAL UNION
SELECT 29, 43, 0  FROM DUAL UNION
SELECT 29, 56, 0  FROM DUAL UNION
SELECT 15, 3, 1  FROM DUAL UNION
SELECT 15, 43, 0  FROM DUAL UNION
SELECT 15, 56, 0  FROM DUAL UNION
SELECT 28, 43, 0  FROM DUAL UNION
SELECT 28, 56, 0  FROM DUAL UNION
SELECT 14, 4, 0  FROM DUAL UNION
SELECT 14, 22, 0  FROM DUAL UNION
SELECT 14, 24, 0  FROM DUAL UNION
SELECT 14, 35, 0  FROM DUAL UNION
SELECT 14, 56, 0  FROM DUAL UNION
SELECT 14, 250, 0  FROM DUAL UNION
SELECT 14, 43, 0  FROM DUAL UNION
SELECT 1, 251, 1 from dual );

commit;